AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://andrae-get-posts/daf6cd909504a3295f9da8f53814ffb3
      Description: ''
      FunctionName: andrae-get-posts
      Handler: index.php
      Layers:
      - arn:aws:lambda:us-east-1:209497400698:layer:php-73:4
      MemorySize: 1024
      Runtime: provided
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
