AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://andrae-get-posts/db892e6c057c2d85672f9f0b727323c9
      Description: ''
      FunctionName: my-function
      Handler: index.php
      Layers:
      - arn:aws:lambda:us-east-1:209497400698:layer:php-73:4
      MemorySize: 1024
      Runtime: provided
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
